console.log("hello")

const checkBox = document.getElementById("switch")
const backGround = document.getElementById("main")
const header = document.getElementById("header")
const toper = document.getElementById("top")
const overview = document.getElementById("overview")
const card1 = document.getElementById("card1")
const card2 = document.getElementById("card2")
const card3 = document.getElementById("card3")
const card4 = document.getElementById("card4")
const box1 = document.getElementById("box1")
const box2 = document.getElementById("box2")
const box3 = document.getElementById("box3")
const box4 = document.getElementById("box4")
const box5 = document.getElementById("box5")
const box6 = document.getElementById("box6")
const box7 = document.getElementById("box7")
const box8 = document.getElementById("box8")

checkBox.addEventListener("change", function () {
  if (this.checked) {
    console.log("checked")
    backGround.classList.add("background_night")
    header.classList.add("night_header")
    toper.classList.add("night_top_bar")
    overview.classList.add("night_overview")
    card1.classList.add("night_nath")
    card2.classList.add("night_nath")
    card3.classList.add("night_nath")
    card4.classList.add("night_nath")
    box1.classList.add("night_view")
    box2.classList.add("night_view")
    box3.classList.add("night_view")
    box4.classList.add("night_view")
    box5.classList.add("night_view")
    box6.classList.add("night_view")
    box7.classList.add("night_view")
    box8.classList.add("night_view")
  } else {
    console.log("not checked")
    backGround.classList.remove("background_night")
    header.classList.remove("night_header")
    toper.classList.remove("night_top_bar")
    overview.classList.remove("night_overview")
    card1.classList.remove("night_nath")
    card2.classList.remove("night_nath")
    card3.classList.remove("night_nath")
    card4.classList.remove("night_nath")
    box1.classList.remove("night_view")
    box2.classList.remove("night_view")
    box3.classList.remove("night_view")
    box4.classList.remove("night_view")
    box5.classList.remove("night_view")
    box6.classList.remove("night_view")
    box7.classList.remove("night_view")
    box8.classList.remove("night_view")
  }
})
